### ISSUE TITLE
Assure that GUID is being set for the bookmarklet nominations/feeds.

### ISSUE THREAD

**Issue by AramZS** [PressForward/pressforward#794]

**Comment by AramZS** [comment]
Please test the whole bookmarklet process, especially check trying to use the bookmarklet as a user who is not authorized to access All Content ( which is the requirement for using Nominate This, right?).

**Comment by regan008** [comment]
I'm getting two errors when using the bookmarklet. The first, on the edit page above the author name and nominate/draft buttons , is: 
```
Notice: Undefined index: content-length in /srv/www/wordpress-default/wp-content/plugins/pressforward/Libraries/PFOpenGraph.php on line 54
```
The second appears once I've nominated the item: 
```
Fatal error: Uncaught Error: Using $this when not in object context in /srv/www/wordpress-default/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php:61 Stack trace: #0 /srv/www/wordpress-default/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php(176): nominate_it() #1 {main} thrown in /srv/www/wordpress-default/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php on line 61
```

**Comment by AramZS** [comment]
Give it another try now, corrected some code issues.

**Comment by regan008** [comment]
Ok, still getting the error below at the top above nominate/draft: 
```
Notice: Undefined index: content-length in /srv/www/wordpress-default/wp-content/plugins/pressforward/Libraries/PFOpenGraph.php on line 54
```

Additionally, nominating the item is still failing but with different errors: 
```
Notice: Undefined property: PressForward\Controllers\PFtoWPUsers::$user_interface in /srv/www/wordpress-default/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php on line 61

Fatal error: Uncaught Error: Call to a member function pf_get_defining_capability_by_role() on null in /srv/www/wordpress-default/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php:61 Stack trace: #0 /srv/www/wordpress-default/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php(176): nominate_it() #1 {main} thrown in /srv/www/wordpress-default/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php on line 61
```

**Comment by regan008** [comment]
@AramZS Not sure if its related, but I'm unable to send items to Nominated from All Content right now.

**Comment by AramZS** [comment]
Huh, not good. Any errors in pf log?

**Comment by regan008** [comment]
Looking through the log now, but I do see this in the console:
![screen shot 2016-07-19 at 10 46 49 am](https://cloud.githubusercontent.com/assets/4553057/16954255/33d4806c-4d9e-11e6-95ad-eb70bb91bdb1.png)

**Comment by AramZS** [comment]
Fixed I think.

**Comment by regan008** [comment]
Fixed!
